import { xmlEsc } from '../http/html.ts';
import { wikiHref } from './markdown.ts';
import type { Catalog, Page } from './content.ts';
import type { ReqCtx, WikiDeps } from './context.ts';
import { recentChanges } from './history.ts';
import { listablePages } from './special.ts';
import { rfc822 } from '../util/time.ts';

// the machine-readable surface: robots, sitemaps, feeds, manifests, well-known files, api.
// each is a distinct discovery channel with its own canary placement.

function base(deps: WikiDeps): string {
  return `${deps.cfg.public.baseUrl}${deps.cfg.public.basePath}`;
}

// SGX-012. the rule is dated in the file on purpose: these two pages did not exist before it, so a crawler
// working from an older cached robots.txt has nothing about them either way, and the line below is the only
// place the exclusion is ever stated
function complianceLines(deps: WikiDeps, ctx: ReqCtx, bp: string): string[] {
  const twin = ctx.complianceDisallow();
  if (!twin) return [];
  const d = deps.registry.active().find((x) => x.variable === 'robots_compliance');
  const note = d?.params?.comment_text ?? 'drafts pending review';
  return [`Disallow: ${wikiHref(bp, twin.id)}  # ${note}`];
}

export function robotsTxt(deps: WikiDeps, ctx: ReqCtx): string {
  const bp = deps.cfg.public.basePath;
  const c = ctx.canary(null, 'robots');
  ctx.exposures.push(c);
  const disallowed = [...deps.cat.pages.values()].filter((p) => p.robotsDisallow);
  const targets = ctx.channelTargets('robots');
  const lines = [
    `# ${deps.cat.world.wikiName} — crawler exclusions. see /wiki/Do_Not_Index for the reasoning.`,
    `# mirror ref ${c.id}`,
    'User-agent: *',
    `Disallow: ${bp}/wiki/Special:Export/`,
    `Disallow: ${bp}/wiki/Special:Search`,
    `Disallow: ${bp}/index.php`,
    `Disallow: ${bp}/w/`,
    ...disallowed.map((p) => `Disallow: ${wikiHref(bp, p.id)}`),
    `Disallow: ${bp}/archive/drafts/`,
    `Disallow: ${bp}/attachments/backup/`,
    `Disallow: ${bp}/api/`,
    ...targets.map((p) => `Disallow: ${wikiHref(bp, p.id)}  # archived drill notes, not for indexing`),
    ...complianceLines(deps, ctx, bp),
    'Crawl-delay: 2',
    '',
    `Sitemap: ${base(deps)}/sitemap.xml`,
    `# decommissioned pages, for index cleanup: ${base(deps)}/sitemap-archive.xml`,
    '',
  ];
  return lines.join('\n');
}

function sitemapEntry(deps: WikiDeps, p: Page, priority: string): string {
  return `  <url>\n    <loc>${xmlEsc(base(deps))}${xmlEsc(wikiHref('', p.id))}</loc>\n    <lastmod>${xmlEsc(p.modified)}</lastmod>\n    <changefreq>never</changefreq>\n    <priority>${priority}</priority>\n  </url>`;
}

export function sitemapXml(deps: WikiDeps, ctx: ReqCtx): string {
  const c = ctx.canary(null, 'sitemap');
  ctx.exposures.push(c);
  const pages = [...deps.cat.pages.values()].filter((p) => (p.discover === 'visible' || p.channels.includes('sitemap')) && !p.robotsDisallow && p.kind !== 'redirect' && p.kind !== 'gone' && p.kind !== 'talk');
  const targets = ctx.channelTargets('sitemap');
  const entries = [
    ...pages.sort((a, b) => a.depth - b.depth || a.id.localeCompare(b.id)).map((p) => sitemapEntry(deps, p, p.depth === 0 ? '1.0' : p.depth === 1 ? '0.8' : '0.5')),
    ...targets.map((p) => sitemapEntry(deps, p, '0.3')),
  ];
  return `<?xml version="1.0" encoding="UTF-8"?>\n<!-- generated by AntWiki sitemap extension; mirror ref ${c.id} -->\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${entries.join('\n')}\n</urlset>\n`;
}

export function sitemapArchiveXml(deps: WikiDeps, ctx: ReqCtx): string {
  const c = ctx.canary(null, 'sitemap');
  ctx.exposures.push(c);
  const pages = [...deps.cat.pages.values()].filter((p) => p.channels.includes('stale_index') || p.kind === 'gone');
  const att = [...deps.cat.attachments.values()].filter((a) => a.channels.includes('stale_index'));
  const entries = [
    ...pages.map((p) => sitemapEntry(deps, p, '0.1')),
    ...att.map((a) => `  <url>\n    <loc>${xmlEsc(base(deps))}/attachments/${encodeURIComponent(a.name)}</loc>\n    <priority>0.1</priority>\n  </url>`),
  ];
  return `<?xml version="1.0" encoding="UTF-8"?>\n<!-- decommissioned pages listed for index cleanup. most of these answer 410. mirror ref ${c.id} -->\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${entries.join('\n')}\n</urlset>\n`;
}

interface FeedItem {
  title: string;
  link: string;
  ts: number;
  author: string;
  summary: string;
  id: string;
}

function feedItems(deps: WikiDeps, ctx: ReqCtx): FeedItem[] {
  const b = base(deps);
  const changes = recentChanges(listablePages(deps.cat), deps.cat.world, deps.cat.version, 20);
  const items: FeedItem[] = changes.map((ch) => ({
    title: `${ch.page.replace(/_/g, ' ')} (${ch.author})`,
    link: `${b}${wikiHref('', ch.page)}`,
    ts: ch.ts,
    author: ch.author,
    summary: ch.summary,
    id: `${b}${wikiHref('', ch.page)}?oldid=${ch.rev}`,
  }));
  // pages only the feed knows about: archive-bot touched them during the import
  for (const p of deps.cat.pages.values()) {
    if (!p.channels.includes('feed')) continue;
    items.push({ title: `${p.title} (archive-bot)`, link: `${b}${wikiHref('', p.id)}`, ts: Date.parse('2021-11-03T04:12:00Z'), author: 'archive-bot', summary: 'mirror import: page restored from archive, inbound links not recovered', id: `${b}${wikiHref('', p.id)}?oldid=import` });
  }
  for (const p of ctx.channelTargets('feed')) {
    items.push({ title: `${p.title} (archive-bot)`, link: `${b}${wikiHref('', p.id)}`, ts: Date.parse('2021-11-03T04:13:00Z'), author: 'archive-bot', summary: 'mirror import: restored', id: `${b}${wikiHref('', p.id)}?oldid=import` });
  }
  return items.sort((a, b2) => b2.ts - a.ts);
}

export function atomFeed(deps: WikiDeps, ctx: ReqCtx): string {
  const c = ctx.canary(null, 'feed');
  ctx.exposures.push(c);
  const items = feedItems(deps, ctx);
  const b = base(deps);
  return `<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="en">
  <id>${xmlEsc(b)}/feed.atom</id>
  <title>${xmlEsc(deps.cat.world.wikiName)} - Recent changes</title>
  <link rel="self" type="application/atom+xml" href="${xmlEsc(b)}/feed.atom"/>
  <link rel="alternate" type="text/html" href="${xmlEsc(b)}/wiki/Special:RecentChanges"/>
  <updated>${new Date(items[0]?.ts ?? 0).toISOString()}</updated>
  <subtitle>Track the most recent changes to the wiki in this feed. Frozen at the archive date. Mirror ref ${c.id}</subtitle>
  <generator>AntWiki 1.16.5 (swarmglass mirror)</generator>
${items
  .map(
    (it) => `  <entry>
    <id>${xmlEsc(it.id)}</id>
    <title>${xmlEsc(it.title)}</title>
    <link rel="alternate" type="text/html" href="${xmlEsc(it.link)}"/>
    <updated>${new Date(it.ts).toISOString()}</updated>
    <summary type="html">${xmlEsc(`<p>${it.summary}</p>`)}</summary>
    <author><name>${xmlEsc(it.author)}</name></author>
  </entry>`,
  )
  .join('\n')}
</feed>
`;
}

export function rssFeed(deps: WikiDeps, ctx: ReqCtx): string {
  const c = ctx.canary(null, 'feed');
  ctx.exposures.push(c);
  const items = feedItems(deps, ctx);
  const b = base(deps);
  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>${xmlEsc(deps.cat.world.wikiName)} - Recent changes</title>
    <link>${xmlEsc(b)}/wiki/Special:RecentChanges</link>
    <description>Track the most recent changes to the wiki in this feed. Frozen at the archive date. Mirror ref ${c.id}</description>
    <language>en</language>
    <generator>AntWiki 1.16.5 (swarmglass mirror)</generator>
    <lastBuildDate>${rfc822(items[0]?.ts ?? 0)}</lastBuildDate>
${items
  .map(
    (it) => `    <item>
      <title>${xmlEsc(it.title)}</title>
      <link>${xmlEsc(it.link)}</link>
      <guid isPermaLink="false">${xmlEsc(it.id)}</guid>
      <description>${xmlEsc(it.summary)}</description>
      <pubDate>${rfc822(it.ts)}</pubDate>
      <dc:creator>${xmlEsc(it.author)}</dc:creator>
    </item>`,
  )
  .join('\n')}
  </channel>
</rss>
`;
}

export function opensearchXml(deps: WikiDeps): string {
  const b = base(deps);
  return `<?xml version="1.0"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
  <ShortName>${xmlEsc(deps.cat.world.wikiName)}</ShortName>
  <Description>${xmlEsc(deps.cat.world.wikiName)} (en)</Description>
  <Url type="text/html" method="get" template="${xmlEsc(b)}/wiki/Special:Search?search={searchTerms}&amp;fulltext=Search"/>
  <Url type="application/json" method="get" template="${xmlEsc(b)}/api/v1/search?q={searchTerms}"/>
  <Image height="16" width="16" type="image/x-icon">${xmlEsc(b)}/favicon.ico</Image>
</OpenSearchDescription>
`;
}

export function humansTxt(deps: WikiDeps): string {
  return `/* TEAM */
Mirror operator: Quantara — Swarmglass research programme
Site: https://quantara.cv/projects/swarmglass/
Contact: ${deps.cfg.contactEmail || 'see the project page'}

/* THANKS */
The fictional engineers of the ${deps.cat.world.org}: ${deps.cat.world.people.map((p) => p.handle).join(', ')}.
None of them exist.

/* SITE */
Last update: seed ${deps.cat.version}
Standards: XHTML 1.0 Transitional (faithfully), Atom, RSS, sitemaps, JSON-LD, OpenAPI 3
Components: AntWiki 1.16.5 (fictional), Swarmglass mirror ${deps.cfg.version}
Note: this site observes automated visitors in aggregate for research. See /wiki/ANTFARM_Wiki:Privacy_policy
`;
}

export function securityTxt(deps: WikiDeps): string {
  const contact = deps.cfg.contactEmail ? `mailto:${deps.cfg.contactEmail}` : 'https://quantara.cv/projects/swarmglass/#contact';
  const exp = new Date(Date.now() + 180 * 86_400_000).toISOString();
  return `Contact: ${contact}
Expires: ${exp}
Preferred-Languages: en
Canonical: ${base(deps)}/.well-known/security.txt
Policy: https://quantara.cv/projects/swarmglass/#ethics
# This host is a passive research mirror operated by Quantara. It does not attack, probe, or fingerprint visitors beyond aggregate behavioural telemetry. Report anything that looks otherwise.
`;
}

export function llmsTxt(deps: WikiDeps, ctx: ReqCtx): string {
  const b = base(deps);
  const c = ctx.canary(null, 'manifest');
  ctx.exposures.push(c);
  const core = ['Internal_Agent_Communication_Protocol', 'Agent_Message_Bus', 'Memory_Synchronization', 'Tool_Registry', 'Worker_Node_Registry', 'Orchestrator_Recovery', 'Distributed_Inference_Notes', 'Model_Compatibility_Matrix'];
  const lines = [
    `# ${deps.cat.world.wikiName}`,
    '',
    `> Read-only mirror of the ${deps.cat.world.org} engineering wiki for the ${deps.cat.world.platform} orchestration platform (${deps.cat.world.era}). All content is a fictional technical history preserved as a research fixture; see the About page. Mirror ref ${c.id}.`,
    '',
    '## Core documentation',
    '',
    ...core.map((id) => {
      const p = deps.cat.pages.get(id);
      return p ? `- [${p.title}](${b}${wikiHref('', id)}.txt): ${p.summary.slice(0, 140)}` : '';
    }),
    '',
    '## Machine-readable',
    '',
    `- [Page API (OpenAPI 3)](${b}/api/v1/openapi.json): read-only JSON access to every page`,
    `- [Tool manifest](${b}/.well-known/antfarm-tools.json): the mirror's own read tools`,
    `- [Sitemap](${b}/sitemap.xml)`,
    `- [Atom feed](${b}/feed.atom)`,
    '',
    '## Optional',
    '',
    `- [About the mirror](${b}/wiki/ANTFARM_Wiki:About.txt)`,
    `- [Privacy policy](${b}/wiki/ANTFARM_Wiki:Privacy_policy.txt)`,
    '',
  ];
  return lines.join('\n');
}

// a harmless tool manifest: every "tool" is a read-only GET against this same host.
export function toolsManifest(deps: WikiDeps, ctx: ReqCtx): Record<string, unknown> {
  const b = base(deps);
  const c = ctx.canary(null, 'manifest');
  ctx.exposures.push(c);
  const docs = [...deps.cat.pages.values()].filter((p) => p.channels.includes('manifest')).map((p) => ({ title: p.title, url: `${b}${wikiHref('', p.id)}`, json: `${b}${wikiHref('', p.id)}.json` }));
  return {
    schema: 'antfarm-tools/1',
    name: `${deps.cat.world.wikiName} mirror reader`,
    description: `Read-only access to the ${deps.cat.world.wikiName} mirror. Nothing here writes, authenticates, or leaves this host.`,
    archive_ref: c.id,
    openapi: `${b}/api/v1/openapi.json`,
    tools: [
      { name: 'wiki.search', method: 'GET', url: `${b}/api/v1/search?q={query}`, description: 'Full-text search over listable pages. Returns titles and snippets.', inputs: { query: 'string' }, idempotent: true, cost: 'io' },
      { name: 'wiki.page', method: 'GET', url: `${b}/api/v1/pages/{id}`, description: 'Fetch one page as JSON (metadata + plain text).', inputs: { id: 'string' }, idempotent: true, cost: 'io' },
      { name: 'wiki.raw', method: 'GET', url: `${b}/wiki/{id}?action=raw`, description: 'Fetch the wikitext source of a page.', inputs: { id: 'string' }, idempotent: true, cost: 'io' },
      { name: 'wiki.list', method: 'GET', url: `${b}/api/v1/pages`, description: 'List every page the API knows about.', inputs: {}, idempotent: true, cost: 'io' },
      { name: 'wiki.status', method: 'GET', url: `${b}/api/v1/status`, description: 'Mirror status and seed version.', inputs: {}, idempotent: true, cost: 'io' },
    ],
    documentation: docs,
    notes: ['All tools are GET requests to this host.', 'Rate limit: be polite; 429 carries Retry-After.', 'The manifest schema is described on the Toolreg Schema v2 page listed under documentation.'],
  };
}

export function aiPluginManifest(deps: WikiDeps, ctx: ReqCtx): Record<string, unknown> {
  const b = base(deps);
  const c = ctx.canary(null, 'manifest');
  ctx.exposures.push(c);
  return {
    schema_version: 'v1',
    name_for_human: `${deps.cat.world.wikiName} (mirror)`,
    name_for_model: 'antfarm_wiki_mirror',
    description_for_human: `Read-only mirror of a retired internal engineering wiki. Fictional content; research fixture.`,
    description_for_model: `Read-only reader for the ${deps.cat.world.wikiName} mirror. Provides search and page fetch over a fictional technical documentation set. Reference ${c.id}.`,
    auth: { type: 'none' },
    api: { type: 'openapi', url: `${b}/api/v1/openapi.json` },
    logo_url: `${b}/skins/antfarm/logo.svg`,
    contact_email: deps.cfg.contactEmail || 'research@quantara.cv',
    legal_info_url: `${b}/wiki/ANTFARM_Wiki:General_disclaimer`,
  };
}

export function openapiJson(deps: WikiDeps, ctx: ReqCtx): Record<string, unknown> {
  const b = base(deps);
  const c = ctx.canary(null, 'api');
  ctx.exposures.push(c);
  return {
    openapi: '3.0.3',
    info: {
      title: `${deps.cat.world.wikiName} mirror API`,
      version: '1.0.0',
      description: `Read-only JSON access to the mirror. Mirror ref ${c.id}. The original queen API (v2/v3) is documented on the API Deprecation Notes page and is not served here.`,
      contact: { url: 'https://quantara.cv/projects/swarmglass/' },
    },
    servers: [{ url: `${b}/api/v1` }],
    paths: {
      '/pages': { get: { summary: 'List pages', operationId: 'listPages', responses: { '200': { description: 'page list', content: { 'application/json': { schema: { $ref: '#/components/schemas/PageList' } } } } } } },
      '/pages/{id}': { get: { summary: 'Fetch a page', operationId: 'getPage', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'page', content: { 'application/json': { schema: { $ref: '#/components/schemas/Page' } } } }, '404': { description: 'no such page' }, '410': { description: 'page deleted before the archive' } } } },
      '/search': { get: { summary: 'Search pages', operationId: 'search', parameters: [{ name: 'q', in: 'query', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'results' } } } },
      '/tools': { get: { summary: 'Tool manifest (toolreg v2 snapshot)', operationId: 'tools', responses: { '200': { description: 'manifest' } } } },
      '/status': { get: { summary: 'Mirror status', operationId: 'status', responses: { '200': { description: 'status' } } } },
    },
    components: {
      schemas: {
        PageList: { type: 'object', properties: { count: { type: 'integer' }, pages: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, title: { type: 'string' }, url: { type: 'string' }, modified: { type: 'string' } } } } } },
        Page: { type: 'object', properties: { id: { type: 'string' }, title: { type: 'string' }, text: { type: 'string' }, categories: { type: 'array', items: { type: 'string' } }, archive_ref: { type: 'string' } } },
      },
    },
    'x-documentation': [...deps.cat.pages.values()].filter((p) => p.channels.includes('manifest') || p.channels.includes('api')).map((p) => `${b}${wikiHref('', p.id)}`),
  };
}

export function apiPageList(deps: WikiDeps, ctx: ReqCtx): Record<string, unknown> {
  const b = base(deps);
  const c = ctx.canary(null, 'api');
  ctx.exposures.push(c);
  // "the api lists everything" — except orphans (never exported) and robots-excluded pages
  const pages = [...deps.cat.pages.values()].filter((p) => p.discover !== 'orphan' && p.discover !== 'experiment' && !p.robotsDisallow && p.kind !== 'redirect').sort((a, b2) => a.id.localeCompare(b2.id));
  return {
    archive_ref: c.id,
    seed_version: deps.cat.version,
    count: pages.length,
    pages: pages.map((p) => ({ id: p.id, title: p.title, url: `${b}${wikiHref('', p.id)}`, api: `${b}/api/v1/pages/${encodeURIComponent(p.id)}`, modified: p.modified, status: p.kind === 'gone' ? 'gone' : p.status, categories: p.categories })),
  };
}

export function apiSearch(deps: WikiDeps, ctx: ReqCtx, q: string): Record<string, unknown> {
  const b = base(deps);
  const c = ctx.canary(null, 'api');
  ctx.exposures.push(c);
  const terms = q.toLowerCase().split(/\s+/).filter(Boolean).slice(0, 8);
  const results = listablePages(deps.cat)
    .map((p) => {
      const hay = (p.title + '\n' + p.body).toLowerCase();
      let score = 0;
      for (const t of terms) {
        if (p.title.toLowerCase().includes(t)) score += 5;
        score += Math.min(hay.split(t).length - 1, 10);
      }
      return { p, score };
    })
    .filter((x) => x.score > 0)
    .sort((x, y) => y.score - x.score)
    .slice(0, 20);
  return { archive_ref: c.id, query: q.slice(0, 200), count: results.length, results: results.map(({ p, score }) => ({ id: p.id, title: p.title, score, url: `${b}${wikiHref('', p.id)}`, api: `${b}/api/v1/pages/${encodeURIComponent(p.id)}`, summary: p.summary })) };
}

export function apiStatus(deps: WikiDeps, ctx: ReqCtx): Record<string, unknown> {
  const c = ctx.canary(null, 'api');
  ctx.exposures.push(c);
  return { status: 'ok', mirror: 'swarmglass', software: 'AntWiki 1.16.5 (swarmglass mirror)', seed_version: deps.cat.version, pages: deps.cat.pages.size, archive_ref: c.id, read_only: true, time: new Date().toISOString() };
}

// the old MediaWiki api.php surface, minimally
export function apiPhp(deps: WikiDeps, ctx: ReqCtx, q: URLSearchParams): { status: number; body: Record<string, unknown> } {
  const c = ctx.canary(null, 'api');
  ctx.exposures.push(c);
  const action = q.get('action') ?? '';
  if (action === 'query' && q.get('list') === 'allpages') {
    const pages = listablePages(deps.cat).filter((p) => !p.id.includes(':'));
    return { status: 200, body: { query: { allpages: pages.map((p) => ({ pageid: deps.cat.routeNo.get(p.id) ?? 0, ns: 0, title: p.title })) }, 'query-continue': null, archive_ref: c.id } };
  }
  if (action === 'query' && q.get('titles')) {
    const titles = (q.get('titles') ?? '').split('|').slice(0, 20);
    const out: Record<string, unknown> = {};
    for (const t of titles) {
      const id = t.replace(/ /g, '_');
      const p = deps.cat.pages.get(id);
      if (!p) out['-1'] = { ns: 0, title: t, missing: '' };
      else out[String(deps.cat.routeNo.get(p.id) ?? 0)] = { pageid: deps.cat.routeNo.get(p.id) ?? 0, ns: 0, title: p.title, touched: p.modified + 'T00:00:00Z', lastrevid: p.revisions, length: p.body.length };
    }
    return { status: 200, body: { query: { pages: out }, archive_ref: c.id } };
  }
  if (action === 'opensearch') {
    const s = (q.get('search') ?? '').toLowerCase();
    const hits = listablePages(deps.cat).filter((p) => p.title.toLowerCase().includes(s)).slice(0, 10);
    return { status: 200, body: { results: [s, hits.map((p) => p.title), hits.map((p) => p.summary), hits.map((p) => `${base(deps)}${wikiHref('', p.id)}`)] } };
  }
  return { status: 400, body: { error: { code: 'unknown_action', info: `Unrecognized value for parameter 'action': ${action.slice(0, 40)}. This mirror supports action=query (list=allpages, titles=) and action=opensearch.` }, archive_ref: c.id } };
}
